---
# See https://github.com/jvautier/project-cli
fullname: jvautier/docker-compose-traefik
description: Docker-compose development stack with traefik.
tags:
  - development
  - docker
  - docker-compose
  - traefik
github:
  has_issues: true
  has_projects: false
  has_wiki: false
