version: "3.7"
networks:
  traefik:
    external: true
services:
  traefik:
    image: traefik:v2.2.1
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--providers.docker"
      - "--api.insecure=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./etc/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./etc/traefik/traefik.config.toml:/etc/traefik/traefik.config.toml:ro
      - ./etc/certs:/etc/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-https.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.traefik-https.entrypoints=https"
      - "traefik.http.routers.traefik-https.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"